[package]
name = "gullkit-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.64"
serde = { version = "1.0.152", default-features = false, features = ["derive", "alloc"] }
thiserror = "1.0.40"
